// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPMD9F8WdalFNUW-jD-8Vw19EinzQP4Z0',
    appId: '1:519380064836:web:e3d7a48dc5eec2cffeba11',
    messagingSenderId: '519380064836',
    projectId: 'cashbackmax-126eb',
    authDomain: 'cashbackmax-126eb.firebaseapp.com',
    storageBucket: 'cashbackmax-126eb.firebasestorage.app',
    measurementId: 'G-MWQKZMG09R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAabiVwodPIpBJjjpM75rD_uL-No3XRvYk',
    appId: '1:519380064836:android:79421634381ef16cfeba11',
    messagingSenderId: '519380064836',
    projectId: 'cashbackmax-126eb',
    storageBucket: 'cashbackmax-126eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-RfgKiVXUfQKp3m81ZN7HQprPWwI4rJg',
    appId: '1:519380064836:ios:9e4906999f18508dfeba11',
    messagingSenderId: '519380064836',
    projectId: 'cashbackmax-126eb',
    storageBucket: 'cashbackmax-126eb.firebasestorage.app',
    iosClientId: '519380064836-597fisq41v4a7io574aqmar3ut4mdkjs.apps.googleusercontent.com',
    iosBundleId: 'com.radra.cashbackRewardsPointsMaximiser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-RfgKiVXUfQKp3m81ZN7HQprPWwI4rJg',
    appId: '1:519380064836:ios:477fe9bcd51280b0feba11',
    messagingSenderId: '519380064836',
    projectId: 'cashbackmax-126eb',
    storageBucket: 'cashbackmax-126eb.firebasestorage.app',
    iosClientId: '519380064836-ut2sd4uk2jfdbjg844i5quh6mgrpgp51.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashbackRewardsPointsMaximiser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPMD9F8WdalFNUW-jD-8Vw19EinzQP4Z0',
    appId: '1:519380064836:web:5ba9df174d017b37feba11',
    messagingSenderId: '519380064836',
    projectId: 'cashbackmax-126eb',
    authDomain: 'cashbackmax-126eb.firebaseapp.com',
    storageBucket: 'cashbackmax-126eb.firebasestorage.app',
    measurementId: 'G-4RTL2XB5WZ',
  );

}